### ISSUE TITLE
OSX Desktop App corrupted

### ISSUE THREAD

**Issue by taiheng** [Protocentral/protocentral-healthypi-v3#1]
Mac executable for HealthyPi GUI is corrupted/non-functional.

<img width="532" alt="screen shot 2017-07-19 at 7 58 32 pm" src="https://user-images.githubusercontent.com/1130292/28394708-f6ad7ec0-6cbc-11e7-92e8-bde92cebabe4.png">

Steps to reproduce:
1. Follow [instructions](http://healthypi.protocentral.com) for getting started with HealthyPi on MacOS.
2. Installed JRE v 8.
3. Download the mac executable

**Comment by protocentralashwin** [comment]
@taiheng Thank you. Please download the app again from the releases section here: https://github.com/Protocentral/protocentral-healthypi-v3/releases/download/v1.0/application.macosx.zip

Also, the issue you mentioned is because of the MacOS gatekeeper system, this is known issue for Java apps on MaxOS. You just need to right click on the app and select "Open". 

More details about this are here: https://support.apple.com/en-us/HT202491

**Comment by taiheng** [comment]
Thanks for responding so quickly! That was it.
